### ISSUE TITLE
希望能设置连续多个iconfont，并且可以自动换行

### ISSUE THREAD

**Issue by chenyucheng97** [DrownCoder/EasyTextView#2]
如题，希望能设置连续多个iconfont，并且可以自动换行

**Comment by DrownCoder** [comment]
你好，目前就是支持连续的多个iconfont，并且左中右的文案都可以设置iconfont，能列举一下具体使用场景吗？

**Comment by DrownCoder** [comment]
> 如题，希望能设置连续多个iconfont，并且可以自动换行

你好，目前就是支持连续的多个iconfont，并且左中右的文案都可以设置iconfont，能列举一下具体使用场景吗？

**Comment by DrownCoder** [comment]
@chenyucheng97 
你好，目前就是支持连续的多个iconfont，并且左中右的文案都可以设置iconfont，能列举一下具体使用场景吗？
