### ISSUE TITLE
有一个资源iconfont.ttf没有提示要复制到项目中去，导致加载异常

### ISSUE THREAD

**Issue by vastsea88** [DrownCoder/EasyTextView#3]
此处异常应该打印出来，或者将提示需要复制iconfont.ttf到项目中去       
 try {
            setTypeface(Typeface.createFromAsset(getContext().getAssets(), "iconfont.ttf"));
        } catch (Exception e) {
            return;
        }

**Comment by DrownCoder** [comment]
@vastsea88  感谢提醒，v1.13版本已增加
