### ISSUE TITLE
在布局中设置了左中右的文字，中是用的textview的text，在代码中单独设置text，左和右就没了

### ISSUE THREAD

**Issue by vastsea88** [DrownCoder/EasyTextView#5]
布局代码：     
   <com.study.xuan.library.widget.EasyTextView
            android:id="@+id/easyText"
            android:paddingTop="5dp"
            android:paddingBottom="5dp"
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            android:gravity="center"
            android:text="&#xe80b;"
            android:textSize="25dp"
            app:textLeft="这真是"
            app:strokeColor="@color/red"
            app:strokeWidth="2dp"
            app:textPadding="20dp"
            app:textRight="一个View" />
在Java代码中调这个方法，
textView.setText("hahahhahah");
就只显示hahahahah了

**Comment by DrownCoder** [comment]
@vastsea88 因为整体是一个TextView，如果setText就相当于把左中右重置了，所以如果只是改中间的文字，可以调用setIcon()这个api
