### ISSUE TITLE
完全没搞懂Span的使用方法

### ISSUE THREAD

**Issue by PiPiCaptain** [DrownCoder/EasyTextView#6]
wiki和代码例子也看了，但是没搞懂Span的用法。我设置了之后，直接不显示了。

我的代码是这样的：

`readText.clearSpan();
readText.setText("已阅读：" + item.getIS_ENABLED() + "/" + item.getNUM());
eadText.addSpanLeft(new ForegroundColorSpan(Color.RED), 0, 2, Spanned.SPAN_EXCLUSIVE_EXCLUSIVE);`

请问有什么问题？

**Comment by DrownCoder** [comment]
`addSpanLeft`这个方法主要是针对左侧已经支持的样式不能够满足需求时使用的，使用方式就是正常的设置span的方式，具体可以查看源码，就是将add后的span设置到文字上。  

如果你的需求只是给左侧文字设置颜色，有两种方式：
1.xml中设置属性textLeftColor
`app:textLeftColor="#ED5151"`
2.java中利用`setTextLeftColor(int color)`设置颜色

目前EasyTextView的左中右三段文字已经支持分别设置颜色，字体，粗体，斜体，具体可以
