### ISSUE TITLE
EasyTextView如何动态设置图标

### ISSUE THREAD

**Issue by dianbaiyizhong** [DrownCoder/EasyTextView#7]
我用setText("&#xe607;")   和setIcon("&#xe607;")   都没效果

**Comment by DrownCoder** [comment]
你好，请问你导入ttf文件了吗？具体可以看[Iconfont官方文档的使用方式](https://www.iconfont.cn/help/detail?spm=a313x.7781069.1998910419.d0091c141&helptype=code)

> 我用setText("") 和setIcon("") 都没效果
